version: '2.1'

services:
  erlang_gobgp:
    image: vdasari/erlango:latest
    container_name: erlang_gobgp
    hostname: erlang_gobgp
    volumes:
        - ${HOME}:${HOME}
    privileged: true
    networks:
      default_net:
        ipv4_address: 10.0.123.10
      network_1:
        ipv4_address: 10.0.100.1
      network_2:
        ipv4_address: 10.0.201.1

  gobgp_1:
    image: vdasari/erlango:latest
    container_name: gobgp_1
    hostname: gobgp_1
    volumes:
        - ${HOME}:${HOME}
    privileged: true
    networks:
      default_net:
        ipv4_address: 10.0.123.100
      network_1:
        ipv4_address: 10.0.100.2
      network_3:
        ipv4_address: 10.0.202.1

  gobgp_2:
    image: vdasari/erlango:latest
    container_name: gobgp_2
    hostname: gobgp_2
    volumes:
        - ${HOME}:${HOME}
    privileged: true
    networks:
      default_net:
        ipv4_address: 10.0.123.200
      network_1:
        ipv4_address: 10.0.100.3

  ryu1:
    image: vdasari/ovs-mn-ryu:latest
    container_name: ryu1
    hostname: ryu1
    volumes:
      - ${HOME}:${HOME}
    ports:
      - "10001:8080"
    entrypoint: |
      bash -c 'bash -s <<EOF
      service openvswitch-switch start
      ryu-manager ryu.app.ofctl_rest ryu.app.rest_vtep ryu.app.simple_switch_13
      EOF'
    privileged: true
    networks:
      default_net:
        ipv4_address: 10.0.123.20
      network_2:
        ipv4_address: 10.0.201.2

  ryu2:
    image: vdasari/ovs-mn-ryu:latest
    container_name: ryu2
    hostname: ryu2
    volumes:
      - ${HOME}:${HOME}
    ports:
      - "10002:8080"
    entrypoint: |
      bash -c 'bash -s <<EOF
      service openvswitch-switch start
      ryu-manager ryu.app.ofctl_rest ryu.app.rest_vtep ryu.app.simple_switch_13
      EOF'
    privileged: true
    networks:
      default_net:
        ipv4_address: 10.0.123.30
      network_3:
        ipv4_address: 10.0.202.2

networks:
  default_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.123.0/24
        gateway: 10.0.123.254
  network_1:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.100.0/24
        gateway: 10.0.100.254
  network_2:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.201.0/24
        gateway: 10.0.201.254
  network_3:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.202.0/24
        gateway: 10.0.202.254
